# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAs < Formula
  desc "Identity switching for git and GitHub CLI"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-as_0.1.0_darwin_amd64.tar.gz"
      sha256 "f9fac9e1dd25a71c15139d20aa58c463922ac10321ae97137db8744359535ea3"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-as_0.1.0_darwin_arm64.tar.gz"
      sha256 "c35e51a3bc99f49374c1ecaa13faa0b56a2814c6926812e6380ef22b8f24b3c0"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-as_0.1.0_linux_amd64.tar.gz"
      sha256 "93412f40254c30b9734ebc921eb766db69184f02f6e8b682779d9ddbb87d3fd4"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-as_0.1.0_linux_arm64.tar.gz"
      sha256 "4ee9ef194f10a918c56f242747dafd21ddeaa49209133de34a52f13462baff25"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end
end
