# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitExplain < Formula
  desc "See your contribution status across git repositories"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-explain_0.1.0_darwin_amd64.tar.gz"
      sha256 "bfc3bacf2a0f88abb4157a61ce68ccd2f86f026fb8db334e3263bdf032a9cb0b"

      def install
        bin.install "git-explain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-explain_0.1.0_darwin_arm64.tar.gz"
      sha256 "d3bb4a40c9bd75406dc6d3b8e4e75e9b3100f07828e1f1df2c58183b8112b612"

      def install
        bin.install "git-explain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-explain_0.1.0_linux_amd64.tar.gz"
      sha256 "781151e00b7060c5ae11e45ac92c07777dbf37ab5a700dee741a90eaa4c7a044"
      def install
        bin.install "git-explain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.0/git-explain_0.1.0_linux_arm64.tar.gz"
      sha256 "3081f58a9b1ad46c77312a6a41191c7c7e4ed825463e4d67f3be219a17069e6d"
      def install
        bin.install "git-explain"
      end
    end
  end
end
