# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: "1.22"

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck      # unchecked errors
    - gosimple      # simplifications
    - govet         # suspicious constructs
    - ineffassign   # unused assignments
    - staticcheck   # static analysis
    - unused        # unused code

    # Additional linters
    - gofmt         # formatting
    - goimports     # import ordering
    - misspell      # spelling in comments
    - gocritic      # opinionated checks
    - revive        # extensible linter (golint successor)
    - unconvert     # unnecessary conversions
    - unparam       # unused parameters
    - gosec         # security issues

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jdevera/git-this-bread

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      # - name: exported  # Too strict for small CLI tools
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G204  # Subprocess with variable - false positive for intentional git CLI usage

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*_generated\\.go$"
